### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [andreacfdez/TeaCozy#6]
Grade: Satisfactory

Summary: Nice job on the project, the site looks good. You used a lot of good techniques and your code is well organized. Take a look at the issues I created as they will give you some tips on how you can improve the project. I would also start taking a look into html5 semantic tags and incorporating them into your code, very big trend in modern html development.
https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

**Comment by andreacfdez** [comment]
Thank a lot for your input. I will surely follow your advice
